global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: node-exporter
    metrics_path: /node-exporter/metrics
    static_configs:
      - targets:
          - host.docker.internal:30080
        labels:
          app: node-exporter
          env: local

  - job_name: kube-state-metrics
    metrics_path: /kube-state/metrics
    static_configs:
      - targets:
          - host.docker.internal:30080
        labels:
          app: kube-state-metrics
          env: local

  - job_name: hello-world
    metrics_path: /hello-world/metrics
    static_configs:
      - targets:
          - host.docker.internal:30080
        labels:
          app: hello-world
          env: local

  - job_name: wifi-probe
    scrape_interval: 5s
    metrics_path: /wifi-probe/metrics
    static_configs:
      - targets:
          - host.docker.internal:30080
        labels:
          app: wifi-probe
          env: local

  - job_name: dns-probe
    scrape_interval: 5s
    metrics_path: /dns-probe/metrics
    static_configs:
      - targets:
          - host.docker.internal:30080
        labels:
          app: dns-probe
          env: local

  - job_name: jitter-probe
    scrape_interval: 5s
    metrics_path: /jitter-probe/metrics
    static_configs:
      - targets:
          - host.docker.internal:30080
        labels:
          app: jitter-probe
          env: local

  - job_name: gateway-monitor
    scrape_interval: 5s
    metrics_path: /gateway-monitor/metrics
    static_configs:
      - targets:
          - host.docker.internal:30080
        labels:
          app: gateway-monitor
          env: local
