apiVersion: v1
kind: Namespace
metadata:
  name: wifi-probe
---
apiVersion: v1
kind: Namespace
metadata:
  name: dns-probe
---
apiVersion: v1
kind: Namespace
metadata:
  name: jitter-probe
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-monitor
---
apiVersion: v1
kind: Namespace
metadata:
  name: alert-receiver
---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
